apiVersion: v1
kind: Service
metadata:
  labels:
    service: payment-service
  name: payment-service
spec:
  ports:
    - name: "50003"
      port: 50003
      targetPort: 50003
  selector:
    service: payment-service
status:
  loadBalancer: {}
