apiVersion: v1
kind: Service
metadata:
  labels:
    service: log-service
  name: log-service
spec:
  ports:
    - name: "50021"
      port: 50021
      targetPort: 50021
  selector:
    service: log-service
status:
  loadBalancer: {}
