apiVersion: v1
kind: Service
metadata:
  labels:
    service: product-postgres
  name: product-postgres
spec:
  ports:
    - name: "51004"
      port: 51004
      targetPort: 5432
  selector:
    service: product-postgres
status:
  loadBalancer: {}
