apiVersion: v1
kind: Service
metadata:
  name: goodfood-payment
spec:
  selector:
    app: goodfood-payment
  ports:
    - name: "grpc"
      port: 50003
      targetPort: 50003
status:
  loadBalancer: {}
