services:
  basket-redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - basket-service-volume:/data
    networks:
      - basket-service-network
    command: redis-server --appendonly yes
    environment:
      REDIS_USERNAME: redis
      REDIS_PASSWORD: password

volumes:
  basket-service-volume:

networks:
  basket-service-network:
