apiVersion: v1
kind: Service
metadata:
  labels:
    service: stock-service
  name: stock-service
spec:
  ports:
    - name: "50009"
      port: 50009
      targetPort: 50009
  selector:
    service: stock-service
status:
  loadBalancer: {}
