apiVersion: v1
kind: Service
metadata:
  labels:
    service: notification-postgres
  name: notification-postgres
spec:
  ports:
    - name: "51022"
      port: 51022
      targetPort: 5432
  selector:
    service: notification-postgres
status:
  loadBalancer: {}
