apiVersion: v1
kind: Service
metadata:
  labels:
    service: notification-service
  name: notification-service
spec:
  ports:
    - name: "50022"
      port: 50022
      targetPort: 50022
  selector:
    service: notification-service
status:
  loadBalancer: {}
