apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: basket-service
spec:
  ingressClassName: nginx
  rules:
    - host: basket.localdev.me
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: basket-service
                port:
                  number: 50002
            path: /