apiVersion: v1
kind: Service
metadata:
  name: goodfood-basket
spec:
  selector:
    app: goodfood-basket
  ports:
    - name: "grpc"
      port: 50002
      targetPort: 50002
status:
  loadBalancer: {}
