apiVersion: v1
kind: Service
metadata:
  labels:
    service: delivery-postgres
  name: delivery-postgres
spec:
  ports:
    - name: "51008"
      port: 51008
      targetPort: 5432
  selector:
    service: delivery-postgres
status:
  loadBalancer: {}
