apiVersion: v1
kind: Service
metadata:
  labels:
    service: delivery-redis
  name: delivery-redis
spec:
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    service: delivery-redis
status:
  loadBalancer: {}
