apiVersion: v1
kind: Service
metadata:
  labels:
    service: delivery-service
  name: delivery-service
spec:
  ports:
    - name: "50008"
      port: 50008
      targetPort: 50008
  selector:
    service: delivery-service
status:
  loadBalancer: {}
