apiVersion: v1
kind: Service
metadata:
  labels:
    service: restaurant-service
  name: restaurant-service
spec:
  ports:
    - name: "50005"
      port: 50005
      targetPort: 50005
  selector:
    service: restaurant-service
status:
  loadBalancer: {}
