apiVersion: v1
kind: Service
metadata:
  labels:
    service: restaurant-postgres
  name: restaurant-postgres
spec:
  ports:
    - name: "51005"
      port: 51005
      targetPort: 5432
  selector:
    service: restaurant-postgres
status:
  loadBalancer: {}
