apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: restaurant-postgres
  name: restaurant-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      service: restaurant-postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        network/goodfood-network: "true"
        service: restaurant-postgres
    spec:
      automountServiceAccountToken: false
      imagePullSecrets:
        - name: registry-credential
      containers:
        - env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: postgres
          image: postgres:latest
          name: restaurant-postgres
          ports:
            - containerPort: 5432
          resources:
            limits:
              memory: 100Mi
              ephemeral-storage: "2Gi"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: goodfood-restaurant-volume
      restartPolicy: Always
      volumes:
        - name: goodfood-restaurant-volume
          persistentVolumeClaim:
            claimName: goodfood-restaurant-volume

