formatters:
  f:
    format: "%(asctime)s %(levelname)s (%(filename)s:%(lineno)d) %(name)s %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S.%3n"
handlers:
  h:
    class: RotatingFileHandler
    filepath: "./logs/app.log"
    mode: O_APPEND
    bufferSize: 0
    # 30 * 1000 ms -> 30 seconds
    bufferFlushTime: 30000
    inputChanSize: 1
    # 100 * 1024 * 1024 -> 100M
    maxBytes: 104857600
    backupCount: 9
    formatter: f
loggers:
  UserServicelogger:
    level: INFO
    handlers: [h]