apiVersion: v1
kind: Service
metadata:
  labels:
    service: promotion-service
  name: promotion-service
spec:
  ports:
    - name: "50006"
      port: 50006
      targetPort: 50006
  selector:
    service: promotion-service
status:
  loadBalancer: {}
