apiVersion: v1
kind: Service
metadata:
  labels:
    service: promotion-postgres
  name: promotion-postgres
spec:
  ports:
    - name: "51006"
      port: 51006
      targetPort: 5432
  selector:
    service: promotion-postgres
status:
  loadBalancer: {}
