services:
  delivery-redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - goodfood-delivery-volume:/data
    networks:
      - goodfood-delivery-network
    command: redis-server --appendonly yes
    environment:
      REDIS_USERNAME: redis
      REDIS_PASSWORD: password
      

  delivery-postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - goodfood-delivery-volume:/var/lib/postgresql/data
    networks:
      - goodfood-delivery-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata

volumes:
  goodfood-delivery-volume:

networks:
  goodfood-delivery-network:
