apiVersion: v1
kind: Service
metadata:
  labels:
    service: basket-redis
  name: basket-redis
spec:
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    service: basket-redis
status:
  loadBalancer: {}
