apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: basket-service
  name: basket-service
spec:
  replicas: 1
  selector:
    matchLabels:
      service: basket-service
  strategy: {}
  template:
    metadata:
      labels:
        network/goodfood-network: "true"
        service: basket-service
    spec:
      automountServiceAccountToken: false
      imagePullSecrets:
        - name: registry-credential
      containers:
        - env:
            - name: AMQP_URL
              valueFrom:
                configMapKeyRef:
                  key: AMQP_URL
                  name: basket--env-docker
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  key: PORT
                  name: basket--env-docker
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  key: REDIS_URL
                  name: basket--env-docker
          image: floriaaan/basket-service:latest
          imagePullPolicy: Always
          name: basket-service
          ports:
            - containerPort: 50002
          resources:
            limits:
              memory: 500Mi
      restartPolicy: Always

