minimumReleaseAgeExclude:
  - micromatch@4.0.8
  - '@babel/runtime@7.26.10'
  - cross-spawn@7.0.5
  - brace-expansion@1.1.12 || 1.1.13 || 1.1.16 || 2.0.2 || 2.0.3 || 2.1.2 || 5.0.8
  - send@0.19.0
  - nanoid@3.3.8
  - glob@10.5.0
  - tar@7.5.3 || 7.5.4 || 7.5.7 || 7.5.8 || 7.5.10 || 7.5.11 || 7.5.16 || 7.5.17 || 7.5.18 || 7.5.19 || 7.5.21
  - minimatch@3.1.3 || 3.1.4 || 9.0.6 || 9.0.7
  - picomatch@2.3.2
  - yaml@2.8.3
  - postcss@8.5.10 || 8.5.12 || 8.5.18
  - '@xmldom/xmldom@0.8.12 || 0.8.13'
  - fast-xml-parser@5.7.0
  - uuid@11.1.1
  - turbo-stream@3.0.0
  - '@babel/plugin-transform-modules-systemjs@7.29.4'
overrides:
  '@babel/plugin-transform-modules-systemjs@>=7.12.0 <=7.29.3': ^7.29.4
  '@xmldom/xmldom@<0.8.12': ^0.8.12
  '@xmldom/xmldom@<0.8.13': ^0.8.13
  brace-expansion@<=5.0.7: ^5.0.8
  fast-xml-parser@<5.7.0: ^5.7.0
  postcss@<8.5.10: ^8.5.10
  postcss@<=8.5.11: ^8.5.12
  postcss@<=8.5.17: ^8.5.18
  send@<0.19.0: ^0.19.0
  tar@<7.5.7: ^7.5.7
  tar@<7.5.8: ^7.5.8
  tar@<=7.5.10: ^7.5.11
  tar@<=7.5.15: ^7.5.16
  tar@<=7.5.16: ^7.5.17
  tar@<=7.5.17: ^7.5.18
  tar@<=7.5.18: ^7.5.19
  tar@<=7.5.2: ^7.5.3
  tar@<=7.5.20: ^7.5.21
  tar@<=7.5.3: ^7.5.4
  tar@<=7.5.9: ^7.5.10
  turbo-stream@<3.0.0: ^3.0.0
  uuid@<11.1.1: ^11.1.1
