apiVersion: v1
kind: Service
metadata:
  name: gateway-loadbalancer
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  type: LoadBalancer
  ports:
    - port: 50000
      targetPort: 50000
  selector:
    app: gateway