name: Log Microservice CI/CD

on:
  push:
    branches: [log]
  pull_request:
    branches: [dev, main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.3

      - name: Build
        run: cd services/log && go build .

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@master
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.3

      - name: Execute tests
        run: cd services/log && go test -v .

  publish:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./services/
          file: ./services/log/Dockerfile
          push: true
          tags: floriaaan/goodfood-log:latest
