name: "Mobile App CI/CD"

on:
  push:
    branches: [app/mobile]
  pull_request:
    branches: [dev, main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: |
          cd ./apps/mobile
          npm ci
      - run: |
          cd ./apps/mobile
          npm run lint


