name: Product Microservice CI/CD

on:
  push:
    branches: [product-service]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "pnpm"
          cache-dependency-path: services/product/pnpm-lock.yaml
      - name: Install dependencies
        run: |
          cd ./services/product
          pnpm install --frozen-lockfile
      - name: Build
        run: |
          cd ./services/product
          pnpm build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@master
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "pnpm"
          cache-dependency-path: services/product/pnpm-lock.yaml
      - name: Install dependencies
        run: |
          cd ./services/product
          pnpm install --frozen-lockfile
      - name: Execute tests
        run: |
          cd ./services/product
          pnpm test

  publish:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./services/
          file: ./services/product/Dockerfile
          push: true
          tags: pierrelbg/goodfood-product:latest