name: Reporting Microservice CI/CD

on:
  push:
    branches: [reporting]
  pull_request:
    branches: [dev, main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"
      - name: Install dependencies
        run: |
          cd ./services/reporting
          dotnet restore
      - name: Build
        run: |
          cd ./services/reporting
          dotnet build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"
      - name: Install dependencies
        run: |
          cd ./services/reporting
          dotnet restore
      - name: Build
        run: |
          cd ./services/reporting
          dotnet build
      - name: Test with the dotnet CLI
        run: |
          cd ./services/reporting
          dotnet test Tests/

  publish:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./services/
          file: ./services/reporting/Dockerfile
          push: true
          tags: floriaaan/goodfood-reporting:latest
