name: "Web App CI/CD"

on:
  push:
    branches: [app/web]
  pull_request:
    branches: [dev, main]

defaults:
  run:
    working-directory: ./apps/web

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm format

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm build
