apiVersion: v1
kind: Service
metadata:
  name: goodfood-product
spec:
  selector:
    app: goodfood-product
  ports:
    - name: "grpc"
      port: 50004
      targetPort: 50004
  type: LoadBalancer
  externalIPs:
  - 192.168.0.10
  - 20.19.144.109