apiVersion: v1
kind: Service
metadata:
  labels:
    service: user-service
  name: user-service
spec:
  ports:
    - name: "50001"
      port: 50001
      targetPort: 50001
  selector:
    service: user-service
status:
  loadBalancer: {}
